/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPublishedRouteImport } from './routes/_app/published'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStyleGuideRouteImport } from './routes/_app/style-guide'
import { Route as AppTrendsRouteImport } from './routes/_app/trends'
import { Route as ApiPublicRunPipelineRouteImport } from './routes/api/public/run-pipeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishedRoute = AppPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStyleGuideRoute = AppStyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicRunPipelineRoute = ApiPublicRunPipelineRouteImport.update({
  id: '/api/public/run-pipeline',
  path: '/api/public/run-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/published': typeof AppPublishedRoute
  '/review': typeof AppReviewRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/style-guide': typeof AppStyleGuideRoute
  '/trends': typeof AppTrendsRoute
  '/api/public/run-pipeline': typeof ApiPublicRunPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/published': typeof AppPublishedRoute
  '/review': typeof AppReviewRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/style-guide': typeof AppStyleGuideRoute
  '/trends': typeof AppTrendsRoute
  '/api/public/run-pipeline': typeof ApiPublicRunPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/published': typeof AppPublishedRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/style-guide': typeof AppStyleGuideRoute
  '/_app/trends': typeof AppTrendsRoute
  '/api/public/run-pipeline': typeof ApiPublicRunPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/published'
    | '/review'
    | '/schedule'
    | '/settings'
    | '/style-guide'
    | '/trends'
    | '/api/public/run-pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/published'
    | '/review'
    | '/schedule'
    | '/settings'
    | '/style-guide'
    | '/trends'
    | '/api/public/run-pipeline'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/published'
    | '/_app/review'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/style-guide'
    | '/_app/trends'
    | '/api/public/run-pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRunPipelineRoute: typeof ApiPublicRunPipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/published': {
      id: '/_app/published'
      path: '/published'
      fullPath: '/published'
      preLoaderRoute: typeof AppPublishedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/style-guide': {
      id: '/_app/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof AppStyleGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trends': {
      id: '/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/run-pipeline': {
      id: '/api/public/run-pipeline'
      path: '/api/public/run-pipeline'
      fullPath: '/api/public/run-pipeline'
      preLoaderRoute: typeof ApiPublicRunPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPublishedRoute: typeof AppPublishedRoute
  AppReviewRoute: typeof AppReviewRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStyleGuideRoute: typeof AppStyleGuideRoute
  AppTrendsRoute: typeof AppTrendsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPublishedRoute: AppPublishedRoute,
  AppReviewRoute: AppReviewRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStyleGuideRoute: AppStyleGuideRoute,
  AppTrendsRoute: AppTrendsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRunPipelineRoute: ApiPublicRunPipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
